### PR TITLE
Makes command output available to another build step

### PR DESCRIPTION
**Pull request by seanturner83**

### CODE REVIEW

**Comment by superbrothers** [comment]
@seanturner83 What use cases do you use this feature?

**Comment by seanturner83** [comment]
For getting information back from the cluster and passing it to another resource (e.g. a slack bot). However, I'm having a bit of trouble with it and I'm wondering whether to refactor into a whole new resource instead.

**Comment by superbrothers** [comment]
Umm, I feel that to use the following tools are better than using concourse for this purpose.

- https://github.com/wongnai/kube-slack
- https://github.com/ultimateboy/slack8s

**Comment by superbrothers** [comment]
This PR is inactivity, so I'll close this PR. If you have an issue yet, please feel free to reopen it. Thanks.

**Pull request closed without merging**
